#!/usr/bin/env ruby

PACKAGE = "web"
TARGET = "assets.go"
RES = {
	# css
	'assets_style_css' => 'assets/style.css',
	'assets_normalize_css' => 'assets/normalize.css',
	# javscript
	'assets_app_js' => 'assets/app.js',
	'assets_jquery2_min_js' => 'assets/jquery2.min.js',
	#'assets_jbone_mini_js' => 'assets/jbone.min.js',
	#'assets_reqwest_min_js' => 'assets/reqwest.min.js',

	# templates
	'view_main' => 'assets/main.html',
}

def gen(pkg, target, res)
	file = "#{pkg}/#{target}"

	open(file, "w") do |f|
		f.puts "package #{pkg}\n\n"
		for var, resfile in res do
			value = IO.read("#{pkg}/#{resfile}")
			f.puts "const #{var} =`#{value}`\n\n"
		end
	end
end

gen PACKAGE, TARGET, RES

# something commandline
# gen res_index template
